apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespace-config
  namespace: devops
spec:
  generators:
  - list:
      elements:
        - filepath: argo-app/values.yaml
          appname: "argoapp"

  template:
    metadata:
      name: '{{appname}}-namespace-config'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: {{ .Values.spec.source.repoURL }}
        targetRevision: HEAD
        path: argo-app
        helm:
          valueFiles:
          - '{{filepath}}'
      destination:
        server: {{ .Values.spec.destination.server }}
        namespace: devops