apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: devops
spec:

  helmDefaults:
    tillerless: true
    tillerNamespace: platform
    atomic: false
    verify: false
    wait: true
    timeout: 1200
    recreatePods: true
    force: true

  syncPolicy:
    automated: {}
  destination:
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: argo-app
    repoURL: {{ .Values.spec.source.repoURL }}