apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: devops
spec:
  syncPolicy:
    automated: {}
  destination:
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: argo-app
    repoURL: {{ .Values.spec.source.repoURL }}