apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces-area-a
  namespace: openshift-gitops
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  destination:
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: namespaces-area-a
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

